### ISSUE TITLE
Checkout Issue with Magento 2 Plugin

### ISSUE THREAD

**Issue by RohanGupta15** [bitpay/bitpay-checkout-magento2#33]
Using the Test environment with Magento 2.3 when using bitpay checkout it sends an order confirmation email before payment is done by the user.
**Expected Outcome**
Order Confirmation Email should be sent after payment is complete. 

**Actual Outcome**
Order Confirmation Email is sent as soon as the user clicks checkout.

**Technical Details:**
Magento Version: 2.3
Plugin Version: 3.14.2002

**Comment by UlyanaKiklevich** [comment]
Any updates on this?

**Comment by RohanGupta15** [comment]
None till now

**Comment by intheshallow** [comment]
Any word at all? This is happening on 2.4 as well.

**Comment by thejoshualewis** [comment]
Hi all, a fix for this should be released later this week, as well as an update to delete an order if a customer closes the invoice page without paying.  It will then re-add everything to the cart to start over.

**Comment by ray-moncada** [comment]
I am having the same or similar issue on production.

Magento 2.3
Bitpay Version 3.14.2002
PHP 7.2

main.ERROR: Notice: Undefined property: stdClass::$data in /usr/share/nginx/mage2/html/vendor/bitpay/module-bpcheckout/Observer/BPRedirect.php on line 308

The modal bitpay payment screen does not load, and buyer gets invoice email.

**Comment by intheshallow** [comment]
Hello,

I see that there were some changes to the core files. I made sure to add these files in, but it still didn’t seem to fix it. Is this still in the works?

**Comment by thejoshualewis** [comment]
These should now be resolved in the latest release.

**Comment by intheshallow** [comment]
This should not be closed. It still doesn’t work. I deleted all old files and replaced with everything on the latest version. I ran my setup upgrade, compiled, and cleared all static files.

**Comment by thejoshualewis** [comment]
Try 6.12.4, its the latest.

Also, I saw someone made a Zendesk ticket with the same issue, if its the same account then it was because that same users account was deactivated for lack of use, and would need to contact our compliance team.

**Comment by intheshallow** [comment]
I downloaded the latest a few hours ago. Was another change made since then?

**Comment by intheshallow** [comment]
This still doesn’t work. I just tried it out. Same error as before.

**Comment by thejoshualewis** [comment]
Send your BitPay email to integrations@bitpay.com and reference this, and I'll look at your account.
